from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

def generate_pdf(report_data, output_path="report.pdf"):
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "📄 MailShield Spoof Scan Report")

    c.setFont("Helvetica", 12)
    y = height - 100
    spacing = 18

    c.drawString(50, y, f"Spoof Score: {report_data['spoof_score']}%")
    y -= spacing
    c.drawString(50, y, f"From: {report_data['headers']['From']}")
    y -= spacing
    c.drawString(50, y, f"Return-Path: {report_data['headers']['Return-Path']}")
    y -= spacing
    c.drawString(50, y, f"Subject: {report_data['headers']['Subject']}")
    y -= spacing
    c.drawString(50, y, f"Domain Age: {report_data['domain_age']} days")
    y -= spacing

    c.drawString(50, y, "Flags:")
    y -= spacing
    for flag in report_data["flags"]:
        c.drawString(70, y, f"- {flag}")
        y -= spacing

    if report_data["phishing_keywords"]:
        c.drawString(50, y, "Phishing Keywords Detected:")
        y -= spacing
        for word in report_data["phishing_keywords"]:
            c.drawString(70, y, f"- {word}")
            y -= spacing

    c.drawString(50, 50, "Report Generated by MailShield")

    c.save()
    return output_path
